### ISSUE TITLE
Removing Count on Icon

### ISSUE THREAD

**Issue by theaulddubliner** [ayoung19/clipboard-history#20]
As above.

Would it be possible to remove the copy count from the icon?

**Comment by ayoung19** [comment]
Yes! You should be able to do this by turning off the "Items Badge Count" setting:

<img width="671" alt="image" src="https://github.com/user-attachments/assets/bf903a84-b527-4179-bd33-3fbf231bd6ad">

Is that not working?

**Comment by theaulddubliner** [comment]
Thanks for that. I actually didn't see the settings button on the popup
initially as it's quite feint.

**Comment by ayoung19** [comment]
Yeah I can see that, thanks for letting me know! I'll add more contrast to it because other people will probably have the same problem in the future.
