### ISSUE TITLE
popup: `EntryList` empty state

### ISSUE THREAD

**Issue by ayoung19** [ayoung19/clipboard-history#6]
The `EntryList` component should show an empty state when there are no rows.

**Comment by morph1nX** [comment]
Would you like to have something like this?

![Screenshot 2024-10-02 201815](https://github.com/user-attachments/assets/b5615cb1-ef83-4c9d-a4ff-3d96d84dcbad)

**Comment by ayoung19** [comment]
Yep! The favorites page should have its own as well. And the message should be different depending on if it's empty due to searching or because there are actually zero items.

**Comment by ayoung19** [comment]
Yeah! My discord username is tph.

And what I mean in my previous comment is the message should be something like "no items found" if it's empty due to a search.
